[package]
name = "gateway-sdk"
version = "0.10.0"
edition = "2024"

# Library configuration
[lib]
name = "gateway_sdk"
path = "src/lib.rs"

[dependencies]
fhevm_gateway_bindings = { git = "https://git@github.com/zama-ai/fhevm.git", tag = "v0.10.3", default-features = false }
kms = { git = "https://git@github.com/zama-ai/kms.git", rev = "bd014fa3b7b7abba6044b294e01d07cca6b49c52", default-features = false }
kms-grpc = { git = "https://git@github.com/zama-ai/kms.git", rev = "bd014fa3b7b7abba6044b294e01d07cca6b49c52", default-features = false }
bc2wrap = { git = "https://git@github.com/zama-ai/kms.git", rev = "bd014fa3b7b7abba6044b294e01d07cca6b49c52", default-features = false }
tfhe = { version = "1.4.0-alpha.3", features = ["boolean", "integer", "zk-pok"] }

alloy = { version = "1.0", default-features = false, features = [
    "essentials",
    "std",
] }
bincode = "1.3"
crypto_box = "0.9.1"
futures-util = "0.3.31"
hex = "0.4.3"
ml-kem = "0.2.1"
rand = "0.9.1"
prost = "0.13.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
thiserror = "2.0.12"
tokio = "1.44.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
    "ansi",
] }
