

[package]
name = "gateway-sdk"
version = "0.1.0"
edition = "2024"

# Library configuration
[lib]
name = "gateway_sdk"
path = "src/lib.rs"

# Binary configuration for the demo service
[[bin]]
name = "fhevm-demo"
path = "src/main.rs"

[dependencies]
fhevm_gateway_rust_bindings = { git = "https://git@github.com/zama-ai/fhevm.git", rev = "2d994c9651b8f141a3ca080c82f5eef2b74577ab", default-features = false }
kms = { git = "https://git@github.com/zama-ai/kms.git", tag = "v0.11.0-26", default-features = false }
kms-grpc = { git = "https://git@github.com/zama-ai/kms.git", tag = "v0.11.0-26", default-features = false }
bc2wrap = { git = "https://git@github.com/zama-ai/kms.git", tag = "v0.11.0-26", default-features = false }

alloy = { version = "1.0", default-features = false, features = [
    "essentials",
    "std",
] }
bincode = "1.3"
crypto_box = "0.9.1"
futures-util = "0.3.31"
hex = "0.4.3"
ml-kem = "0.2.1"
rand = "0.9.1"
prost = "0.13.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tfhe = { version = "1.3.2", features = ["boolean", "integer", "zk-pok"] }
thiserror = "2.0.12"
tokio = "1.44.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
    "ansi",
] }
