[package]
name = "fhevm-listener"
version = "0.0.1"
edition = "2021"
license.workspace = true

[[bin]]
path = "src/bin/main.rs"
name = "fhevm_listener"
test = false
bench = false

[dependencies]
# external dependencies
alloy-provider = "1.0.9"
alloy-eips = "1.0.9"
alloy-rpc-types = "1.0.9"
alloy-sol-types = "1.2.0"

# workspace dependencies
alloy = { workspace = true, features = ["contract", "json", "providers", "provider-ws", "pubsub", "rpc-types", "sol-types"] }
alloy-primitives = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# local dependencies
fhevm-engine-common = { path = "../fhevm-engine-common" }

[dev-dependencies]
anyhow = { workspace = true }
serial_test = { workspace = true }

[build-dependencies]
foundry-compilers = { workspace = true }
foundry-compilers-artifacts = "0.13"
semver = { workspace = true }
