scDeploy:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm/gateway-contracts
    tag: "v0.7.0"
  configmap:
    name: "gateway-sc-addresses"
  env:
    - name: HARDHAT_NETWORK
      value: "staging"
    - name: RPC_URL
      value: "http://gateway-anvil-node:8546"
    - name: DEPLOYER_PRIVATE_KEY
      value: "0xe746bc71f6bee141a954e6a49bc9384d334e393a7ea1e70b50241cb2e78e9e4c"
    # 1) Initial Contract Deployment Config
    - name: CHAIN_ID_GATEWAY
      value: "54321"
    - name: DEPLOYER_ADDRESS
      value: "0xCf28E90D4A6dB23c34E1881aEF5fd9fF2e478634"
    - name: PAUSER_ADDRESS
      value: "0xCf28E90D4A6dB23c34E1881aEF5fd9fF2e478634"
    - name: PROTOCOL_NAME
      value: "Zama"
    - name: PROTOCOL_WEBSITE
      value: "zama.ai"
    - name: MPC_THRESHOLD
      value: "1"
    - name: NUM_KMS_NODES
      value: "4"
    # USER_DECRYPTION_THRESHOLD=(2*MPC_THRESHOLD) + 1
    - name: USER_DECRYPTION_THRESHOLD
      value: "3"
    # PUBLIC_DECRYPTION_THRESHOLD=floor(NUM_KMS_NODES/2) + 1
    # This threshold must match the one defined for the host
    - name: PUBLIC_DECRYPTION_THRESHOLD
      value: "3"
    - name: KMS_TX_SENDER_ADDRESS_0
      value: "0x87B8588FE7b273A0707b430fd26E01ecb014417A" # 0x2fa595e2a6ecf65fb93c06ffe4dd444c1d9d72746a61b09a0eef2f7ee52ff8af
    - name: KMS_TX_SENDER_ADDRESS_1
      value: "0x264D261d719aFD70F4d72f529D644A56327dCf2e" # 0xb97704c21e5c50e06272fbe1db3b4ba21d360e2dc81cde169ad14c1ea21a85a4
    - name: KMS_TX_SENDER_ADDRESS_2
      value: "0xEEcE0864CCAB13866AdCa8319B278b6d4af40484" # 0xb72ad6f093ee103cc35d376b57901c17abb1a1fe47b82ba385bebaabfe559d5a
    - name: KMS_TX_SENDER_ADDRESS_3
      value: "0x0425EB924AcCc9199ebf98038Dea9cA4823bC3e9" # 0xdc68f74b49335532da848d8d7cbce641d5920256ca76798cbb128c7165a10f27
    - name: KMS_SIGNER_ADDRESS_0
      value: "0xB01Df3Cf07E867c0E73785CE4b095408B25b1adE"
    - name: KMS_SIGNER_ADDRESS_1
      value: "0xd9cCc0D6d3f703FEF2FA8963715695f7A43F334D"
    - name: KMS_SIGNER_ADDRESS_2
      value: "0x78d72267C5cb71DdfEb5737e3CAB7878998C982C"
    - name: KMS_SIGNER_ADDRESS_3
      value: "0xB78Ff45392840d5d9382A0fD2C3A9454ca396193"
    - name: KMS_NODE_IP_ADDRESS_0
      value: ""
    - name: KMS_NODE_IP_ADDRESS_1
      value: ""
    - name: KMS_NODE_IP_ADDRESS_2
      value: ""
    - name: KMS_NODE_IP_ADDRESS_3
      value: ""
    - name: KMS_NODE_DA_URL_0
      value: ""
    - name: KMS_NODE_DA_URL_1
      value: ""
    - name: KMS_NODE_DA_URL_2
      value: ""
    - name: KMS_NODE_DA_URL_3
      value: ""
    - name: NUM_COPROCESSORS
      value: "1"
    - name: COPROCESSORS_FEATURE_SET
      value: "1"
    - name: COPROCESSOR_NAME_0
      value: "Coprocessor 1"
    - name: COPROCESSOR_TX_SENDER_ADDRESS_0
      value: "0x6254A198F67ad40290a2E7B48aDB2d19B71f67BD"
    - name: COPROCESSOR_SIGNER_ADDRESS_0
      value: "0x6254A198F67ad40290a2E7B48aDB2d19B71f67BD"
    - name: COPROCESSOR_S3_BUCKET_URL_0
      value: "http://example.com"
    - name: FHE_PARAMS_NAME
      value: "test"
    - name: FHE_PARAMS_DIGEST
      value: "0x0000000000000000000000000000000000000000000000000000000000000000"
    # 2) Add Host Chains Config
#    - name: NUM_HOST_CHAINS
#      value: "1"
#    - name: HOST_CHAIN_CHAIN_ID_0
#      value: "12345"
#    - name: HOST_CHAIN_FHEVM_EXECUTOR_ADDRESS_0
#      valueFrom:
#        configMapKeyRef:
#          name: host-sc-addresses
#          key: exec.address
#    - name: HOST_CHAIN_ACL_ADDRESS_0
#      valueFrom:
#        configMapKeyRef:
#          name: host-sc-addresses
#          key: acl.address
#    - name: HOST_CHAIN_NAME_0
#      value: ""
#    - name: HOST_CHAIN_WEBSITE_0
#      value: ""

  verifyContracts: false
  deployCommands:
    - "npx --no-install hardhat task:deployAllGatewayContracts"
    #- "npx --no-install hardhat task:deployEmptyUUPSProxies"
    #- "npx --no-install hardhat task:addHostChainsToGatewayConfig"

persistence:
  enabled: true
  volumeClaim:
    create: true
    name: "gateway-contracts"
    storageClassName: "standard"
    storageCapacity: 1Gi