scDeploy:
  enabled: true
  image:
    name: ghcr.io/zama-ai/fhevm/host-contracts
    tag: v0.7.0-rc2
  configmap:
    name: "host-sc-addresses"
  env:
    - name: HARDHAT_NETWORK
      value: "staging"
    - name: RPC_URL
      value: "http://host-anvil-node:8545"
    - name: CHAIN_ID_GATEWAY
      value: "54321"
    - name: DEPLOYER_PRIVATE_KEY
      value: "2d24c36c57e6bfbf90c43173481cc00edcbd1a3922de5e5fdb9aba5fc4e0fafd" # accounts[9]
    - name: PAUSER_ADDRESS
      value: "0xa44366bAA26296c1409AD1e284264212029F02f1" # accounts[2]
    - name: DECRYPTION_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: gateway-sc-addresses
          key: decryption.address
    - name: INPUT_VERIFICATION_ADDRESS
      valueFrom:
        configMapKeyRef:
          name: gateway-sc-addresses
          key: input_verification.address
    - name: NUM_KMS_NODES
      value: "4"
    # PUBLIC_DECRYPTION_THRESHOLD=floor(NUM_KMS_NODES/2) + 1
    # This threshold must match the one defined for the gateway
    - name: PUBLIC_DECRYPTION_THRESHOLD
      value: "3"
    - name: KMS_SIGNER_ADDRESS_0
      value: "0xB01Df3Cf07E867c0E73785CE4b095408B25b1adE"
    - name: KMS_SIGNER_ADDRESS_1
      value: "0xd9cCc0D6d3f703FEF2FA8963715695f7A43F334D"
    - name: KMS_SIGNER_ADDRESS_2
      value: "0x78d72267C5cb71DdfEb5737e3CAB7878998C982C"
    - name: KMS_SIGNER_ADDRESS_3
      value: "0xB78Ff45392840d5d9382A0fD2C3A9454ca396193"
    - name: NUM_COPROCESSORS
      value: "1"
    - name: COPROCESSOR_SIGNER_ADDRESS_0
      value: "0x6254A198F67ad40290a2E7B48aDB2d19B71f67BD"
  verifyContracts: false
  deployCommands:
    - "npx --no-install hardhat task:deployAllHostContracts"
  resources:
    limits:
      cpu: 1
      memory: 4Gi

scDebug:
  enabled: false

persistence:
  enabled: true
  volumeClaim:
    create: true
    name: "host-contracts"
    storageClassName: "standard"
    storageCapacity: 1Gi