nameOverride:
replicaCount: 1

image:
  name: ghcr.io/zama-ai/fhevm-relayer
  tag: 7e5f37e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: fhevm_PRIVATE_KEY
    value: "0x2e014a0b381171ae1ec813ccb82e1d9fed7e6cf2d860844e43e4ac072bf0e50a"
  - name: GATEWAY_PRIVATE_KEY
    value: "0xcb97ef45d352446a6adf810cf8f63c73ada027160c271da9bb8cfcb3d944d257"
  - name: DECRYPTION_ORACLE_ADDRESS
    valueFrom:
      configMapKeyRef:
        name: host-sc-addresses
        key: decryptionoracle.address
  - name: TFHE_EXECUTOR_ADDRESS
    valueFrom:
      configMapKeyRef:
        name: host-sc-addresses
        key: exec.address
  - name: DECRYPTION_MANAGER_ADDRESS
    valueFrom:
      configMapKeyRef:
        name: gateway-sc-addresses
        key: fhevm.address
  - name: ZKPOK_MANAGER_ADDRESS
    valueFrom:
      configMapKeyRef:
        name: gateway-sc-addresses
        key: zkpok_manager.address

config:
  environment: staging
  inputproof:
    url: "0.0.0.0:3000"
  keyurl:
      fhe_public_key:
        data_id: "fhe-public-key-data-id"
        url: "http://minio.fhevm.svc.cluster.local:9000/kms-public/kms/PUB/PublicKey/408d8cbaa51dece7f782fe04ba0b1c1d017b1088"
      crs:
        data_id: "crs-data-id"
        url: "http://minio.fhevm.svc.cluster.local:9000/kms-public/kms/PUB/CRS/a5fedad3fd734a598fb67452099229445cb68447"
  networks:
    fhevm:
      ws_url: "ws://host-anvil-node:8545"
      http_url: "http://host-anvil-node:8545"
      chain_id: 12345
      retry_delay: 1000
      max_reconnection_attempts: 3
    rollup:
      ws_url: "ws://gateway-anvil-node:8546"
      http_url: "http://gateway-anvil-node:8546"
      chain_id: 54321
      retry_delay: 1000
      max_reconnection_attempts: 3
  transaction:
    private_key_fhevm: fhevm_PRIVATE_KEY
    private_key_gateway: GATEWAY_PRIVATE_KEY
    gas_limit: 150000
    max_priority_fee: 2000000000
    timeout_secs: 60
    confirmations: 1
    retry:
      enabled: false
      max_attempts: 3
      base_delay_secs: 2
      max_delay_secs: 60
  contracts:
    decryption_oracle_address: 0xAb30999D17FAAB8c95B2eCD500cFeFc8f658f15d
    tfhe_executor_address: 0x12B064FB845C1cc05e9493856a1D637a73e944bE
    decryption_manager_address: 0x5ffdaAB0373E62E2ea2944776209aEf29E631A64
    zkpok_manager_address: 0x812b06e1CDCE800494b79fFE4f925A504a9A9810
  log:
    level: "info"
    format: "pretty"
    show_file_line: false
    show_thread_ids: false
    show_timestamp: true
  db_path_rocksdb: "./.database"
  staging:
    verbose_errors: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi