services:
  host-sc-deploy:
    container_name: host-sc-deploy
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    build:
      context: ../../../host-contracts
      dockerfile: Dockerfile
      cache_from:
        - ${FHEVM_CACHE_FROM:-type=gha}
      cache_to:
        - ${FHEVM_CACHE_TO:-type=gha,mode=max}
    env_file:
      - ../env/staging/.env.host-sc.local
    command:
      - npx hardhat task:deployAllHostContracts
    volumes:
      - addresses-volume:/app/addresses  # workdir in host's Dockerfile is /app

  host-sc-add-pausers:
    container_name: host-sc-add-pausers
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    build:
      context: ../../../host-contracts
      dockerfile: Dockerfile
      cache_from:
        - ${FHEVM_CACHE_FROM:-type=gha}
      cache_to:
        - ${FHEVM_CACHE_TO:-type=gha,mode=max}
    env_file:
      - ../env/staging/.env.host-sc.local
    command:
      - npx hardhat task:addHostPausers
    depends_on:
      host-sc-deploy:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because the PauserSet
    # contract is compiled, and it imports these addresses.
    volumes:
      - addresses-volume:/app/addresses  # workdir in host's Dockerfile is /app

volumes:
  addresses-volume:
