services:
  host-node:
    container_name: fhevm-host-node
    image: ghcr.io/foundry-rs/foundry:v1.3.5
    env_file:
      - ../env/staging/.env.host-node.local
    entrypoint:
      - anvil
      - --block-time
      - "1"
      - --host
      - 0.0.0.0
      - --port
      - "8545"
      - --chain-id
      - "12345"
      - --accounts
      - "120"
      - --mnemonic
      - "${MNEMONIC}"
    ports:
      - "8545:8545"
