services:
  host-node:
    container_name: fhevm-host-node
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    env_file:
      - ../env/staging/.env.host.local
    entrypoint:
      - anvil
      - --block-time
      - "1"
      - --host
      - 0.0.0.0
      - --port
      - "8545"
      - --chain-id
      - "12345"
      - --accounts
      - "120"
      - --mnemonic
      - "${MNEMONIC}"
    ports:
      - "8545:8545"

  host-sc-deploy:
    container_name: fhevm-host-sc-deploy
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    build:
      context: ../../../host-contracts
      dockerfile: Dockerfile
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    env_file:
      - ../env/staging/.env.host.local
    command:
      - npx hardhat task:deployAllHostContracts
    depends_on:
      host-node:
        condition: service_started
