# Assuming port forwarding at least one validator node and the kv-store
# key_endpoint="https://kms-dev-v1.s3.eu-west-3.amazonaws.com/centralized/PUB/PublicKey"
# TODO: Use real keys once that's solved
s3_endpoint = "/Users/luismontero/Documents/work/zama/kms-core/blockchain/simulator/fake_key/"
key_id = "408d8cbaa51dece7f782fe04ba0b1c1d017b1088"
object_folder = ["PUB"]
validator_addresses = ["http://localhost:9090"]
http_validator_endpoints = ["http://localhost:36657"]
kv_store_address = "http://localhost:8088"
contract = "wasm1wpqx4mhe5hmgte8s4etam4syfxjt83zwvejhgsmcludfpt5hd6kq8lkreu"
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
faucet_address = "http://localhost:8000"
