tick_interval_secs = 1
storage_path = "./temp/events.toml"

[oracle]
addresses = ["http://localhost:26657"]

[blockchain]
addresses = ["http://localhost:9090"]
contract = "wasm1yyca08xqdgvjz0psg56z67ejh9xms6l436u8y58m82npdqqhmmtqas0cl7"

[blockchain.signkey]
# It should be either mnemonic or bip32
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"
bip32 = "xprv9s21ZrQH143K3FQVQn1Z6"

[blockchain.fee]
denom = "ucosm"
amount = 3000000

[core]
addresses = ["http://localhost:50051"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.decryption]
initial_wait_time = 3
retry_interval = 2
max_poll_count = 36

[core.timeout_config.insecure_key_gen]
initial_wait_time = 10
retry_interval = 10
max_poll_count = 200

[core.timeout_config.reencryption]
initial_wait_time = 2
retry_interval = 1
max_poll_count = 36

[core.timeout_config.zkp]
initial_wait_time = 1
retry_interval = 1
max_poll_count = 24

[tracing]
service_name = "kms-connector-4"
endpoint = "http://otelcol:4317"

[store]
url = "http://localhost:8088"
