[package]
name = "solc-build-utils"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
foundry-compilers = { workspace = true }
fs4 = { workspace = true }
semver = { workspace = true }
