name: fhevm

services:
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  db-migration:
    container_name: db-migration
    build:
      context: ../../../.
      dockerfile: coprocessor/fhevm-engine/Dockerfile.workspace
      target: db-migration
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
      ACL_CONTRACT_ADDRESS: "0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2"
    command:
      - /initialize_db.sh
    healthcheck:
      test: [ "CMD-SHELL", "psql --version" ]
      interval: 15s
      timeout: 5s
      retries: 1
      start_period: 5s
    volumes:
      - ../fhevm-keys:/fhevm-keys
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
