[package]
name = "scheduler"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace dependencies
anyhow = { workspace = true }
daggy = { workspace = true }
hex = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
rayon = { workspace = true }
tfhe = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }

# local dependencies
fhevm-engine-common = { path = "../fhevm-engine-common" }

[features]
nightly-avx512 = ["tfhe/nightly-avx512"]
gpu = ["tfhe/gpu"]
