apiVersion: v2
name: fhevm-sql-exporter
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: prometheus-sql-exporter
    repository: oci://ghcr.io/prometheus-community/charts
    version: 0.4.0
