name: zama-dev

services:

  gateway-store:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.9.0-rc18-e2e-testing
    command:
      - "kv_store"
    ports:
      - "8088:8088"

  kms-validator:
    image: ghcr.io/zama-ai/kms-blockchain-asc-dev:v0.9.0-rc18-e2e-testing
    ports:
      - "36656:26656"
      - "36657:26657"
      - "1317:1317"
      - "9090:9090"
    entrypoint: [ "/app/bootstrap.sh" ]
    volumes:
      - ../asc/asc.wasm:/app/asc.wasm
      - ../asc/ethereum_ipsc.wasm:/app/ethereum_ipsc.wasm
      - ../asc/bootstrap_asc.sh:/app/bootstrap.sh
    healthcheck:
      test: "wget -Sq --spider http://localhost:26657/status"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s

  connector:
    image: ghcr.io/zama-ai/kms-blockchain-connector-dev:v0.9.0-rc18-e2e-testing
    command:
      - "kms-blockchain-connector"
    environment:
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-validator:9090
      - ASC_CONN__CORE__ADDRESSES=http://kms-core:50051
      - ASC_CONN__STORE__URL=http://gateway-store:8088
      - ASC_CONN__BLOCKCHAIN__CONTRACT=wasm1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqr5j2ht
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      kms-validator:
        condition: service_healthy
      kms-core:
        condition: service_healthy

  kms-core:
    image: ghcr.io/zama-ai/kms-service-dev:v0.9.0-rc18-e2e-testing
    environment:
      - RUST_LOG=info
    volumes:
      - $PWD/res/keys:/app/kms/core/service/keys:Z
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
  #  gateway:
  #    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.9.0-rc18-e2e-testing
  #    ports:
  #      - "7077:7077"
  #    command:
  #      - "gateway"
  #    volumes:
  #      - ../default.toml:/app/gateway/config/default.toml:Z
  #    environment:
  #      - GATEWAY__ETHEREUM__LISTENER_TYPE=COPROCESSOR
  #      - GATEWAY__ETHEREUM__CHAIN_ID=12345
  #      - GATEWAY__ETHEREUM__WSS_URL=ws://localhost:8746
  #      - GATEWAY__ETHEREUM__HTTP_URL=http://localhost:8545
  #      - GATEWAY__ETHEREUM__FHE_LIB_ADDRESS=000000000000000000000000000000000000005d
  #      - GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS=096b4679d45fB675d4e2c1E4565009Cec99A12B1
  #      - GATEWAY__ETHEREUM__ACL_ADDRESS=05fD9B5EFE0a996095f42Ed7e77c390810CF660c
  #      - GATEWAY__ETHEREUM__COPROCESSOR_API_KEY=api-key
  #      - GATEWAY__ETHEREUM__COPROCESSOR_URL=http://127.0.0.1:50055
  #      - GATEWAY__ETHEREUM__CONTRACT_ADDRESS=wasm1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqr5j2ht
  #      - GATEWAY__ETHEREUM__KMSVERIFIER_VC_ADDRESS=857Ca72A957920Fa0FB138602995839866Bd4005
  #      - GATEWAY__KMS__KEY_ID=408d8cbaa51dece7f782fe04ba0b1c1d017b1088
  #      - GATEWAY__ETHEREUM__RELAYER_KEY=7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67
  #      - RUST_BACKTRACE=1
  #    depends_on:
  #      kms-validator:
  #        condition: service_healthy
  # fhevm-validator:
  #   environment:
  #     - TFHE_EXECUTOR_CONTRACT_ADDRESS=0x05fD9B5EFE0a996095f42Ed7e77c390810CF660c
  #   image: ghcr.io/zama-ai/ethermint-dev-node:v0.5.1
  #   ports:
  #     - "26656-26657:26656-26657"
  #     - "8545-8546:8545-8546"
  #   volumes:
  #     - $PWD/network-fhe-keys:/network-fhe-keys:Z
  #     - ../setup.sh:/config/setup.sh:Z
  #   security_opt:
  #     - no-new-privileges:true
  #   healthcheck:
  #     test: "curl -s -H \"Connection: Upgrade\" -H \"Upgrade: websocket\"  http://localhost:8546"
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #     start_period: 20s
