[package]
name = "gateway-stress"
version = "0.9.0"
edition = "2024"

[dependencies]
fhevm_gateway_bindings = { git = "https://github.com/zama-ai/fhevm.git", tag = "v0.9.0", default-features = false }
gateway-sdk = { git = "https://github.com/zama-ai/fhevm.git", tag = "v0.9.0", default-features = false }

alloy = { version = "1.0", default-features = false, features = [
    "essentials",
    "reqwest-rustls-tls",
    "std",
    "provider-ws",
    "signer-aws",
    "signer-mnemonic",
] }
anyhow = "1.0.98"
async-trait = { version = "0.1.88", default-features = false }
aws-config = { version = "1.8.2", default-features = true }
aws-sdk-kms = { version = "1.79.0", default-features = true }
aws-sdk-s3 = { version = "1.98.0", default-features = true }
clap = { version = "4.5.38", features = ["cargo", "derive"] }
config = { version = "0.15.13", default-features = false, features = ["toml"] }
csv = { version = "1.3.1", default-features = false }
futures = { version = "0.3.31", default-features = false }
humantime = "2.2.0"
humantime-serde = "1.1.1"
indicatif = { version = "0.18.0", default-features = true, features = [
    "tokio",
] }
rustls = "0.23.31"
serde = { version = "1.0.226", default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0.141", default-features = false, features = [
    "std",
] }
sqlx = { version = "0.8.6", default-features = false, features = [
    "chrono",
    "derive",
    "macros",
    "postgres",
    "runtime-tokio",
    "time",
    "tls-rustls",
] }
tokio = { version = "1.47.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "sync",
] }
tokio-util = "0.7.15"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", default-features = true, features = [
    "env-filter",
] }
rand = "0.9.2"
