[package]
name = "gw-listener"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
connector-utils.workspace = true
fhevm_gateway_bindings.workspace = true

actix-web.workspace = true
alloy.workspace = true
anyhow.workspace = true
prometheus.workspace = true
sqlx.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
connector-utils = { workspace = true, features = ["tests"] }
rstest.workspace = true
serial_test.workspace = true
tempfile.workspace = true
testcontainers.workspace = true
toml.workspace = true
tracing-test.workspace = true

[[bin]]
name = "gw-listener"
path = "src/bin/gw_listener.rs"
