[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', "dependencies"]
test = 'test'
cache_path  = 'cache_forge'
solc = '0.8.24'

remappings = [
    '@fhevm-foundry/=./fhevm-foundry/',
    '@fhevm-host-contracts/=./',
    'forge-std/=dependencies/forge-std-1.11.0/src/'

]

[fuzz]
# The number of fuzz runs for fuzz tests
runs = 2560

[profile.default.invariant]
runs = 96
depth = 24
fail_on_revert = false

[profile.invariant_stress.invariant]
runs = 256
depth = 64
fail_on_revert = false

[dependencies]
forge-std = "1.11.0"
