{{- if .Values.dbMigration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migration-{{ .Release.Revision }}
  labels:
    app: coprocessor-db-migration
    app.kubernetes.io/name: {{ .Release.Name }}-db-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-needs": "{{ .Release.Name }}-config-setup-{{ .Release.Revision }}"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: coprocessor-db-migration
        app.kubernetes.io/name: {{ .Release.Name }}-db-migration
    spec:
      restartPolicy: Never
      {{- if and .Values.dbMigration.affinity .Values.dbMigration.affinity.enabled }}
      affinity:
{{ toYaml (omit .Values.dbMigration.affinity "enabled") | indent 8 }}
      {{- end }}
      {{- if and .Values.dbMigration.tolerations .Values.dbMigration.tolerations.enabled }}
      tolerations:
{{ toYaml .Values.dbMigration.tolerations.items | indent 8 }}
      {{- end }}
      {{- if .Values.dbMigration.serviceAccountName }}
      serviceAccountName: {{ .Values.dbMigration.serviceAccountName }}
      {{- end }}
      initContainers:
      - name: fetch-pub-key-matter
        image: netdata/wget:latest
        command:
          - sh
        args:
          - -c
          - |
            set -ex
            wget {{ .Values.dbMigration.insertInitContainer.pksURL }} -O /fhevm-keys/pks
            sha256sum /fhevm-keys/pks
            wget {{ .Values.dbMigration.insertInitContainer.sksURL }} -O /fhevm-keys/sks
            sha256sum /fhevm-keys/sks
            wget {{ .Values.dbMigration.insertInitContainer.publicParamsURL }} -O /fhevm-keys/pp
            sha256sum /fhevm-keys/pp
            wget {{ .Values.dbMigration.insertInitContainer.snsURL }} -O /fhevm-keys/sns_pk
            sha256sum /fhevm-keys/sns_pk
        volumeMounts:
          - mountPath: /fhevm-keys
            name: cache-volume
      containers:
      - name: db-migration
        image: {{ .Values.dbMigration.image.name }}:{{ .Values.dbMigration.image.tag }}
        env:
{{ toYaml .Values.dbMigration.env | nindent 12 }}
        resources:
          requests:
            cpu: {{ .Values.dbMigration.resources.requests.cpu | default "100m" }}
            memory: {{ .Values.dbMigration.resources.requests.memory | default "256Mi" }}
          limits:
            cpu: {{ .Values.dbMigration.resources.limits.cpu | default "500m" }}
            memory: {{ .Values.dbMigration.resources.limits.memory | default "512Mi" }}
        volumeMounts:
          - mountPath: /fhevm-keys/pks
            name: cache-volume
            subPath: pks
            readOnly: true
          - mountPath: /fhevm-keys/sks
            name: cache-volume
            subPath: sks
            readOnly: true
          - mountPath: /fhevm-keys/sns_pk
            name: cache-volume
            subPath: sns_pk
            readOnly: true
          - mountPath: /fhevm-keys/pp
            name: cache-volume
            subPath: pp
            readOnly: true
      volumes:
        - name: cache-volume
          emptyDir: 
            sizeLimit: 3Gi
{{- end -}}
