name: httpz-layer1

services:
  anvil-node:
    container_name: anvil-node
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint:
      - anvil
      - --block-time
      - "0.5"
      - --host
      - 0.0.0.0
      - --port
      - "8545"
      - --chain-id
      - "12345"
      - --accounts
      - "15"
      - --mnemonic
      - "adapt mosquito move limb mobile illegal tree voyage juice mosquito burger raise father hope layer"
    ports:
      - "8545:8545"
    volumes:
      - .:/anvil

  httpz-sc-deploy:
    container_name: httpz-sc-deploy
    build:
      context: ../
      dockerfile: contracts/operations/docker/ci.dockerfile
      tags:
        - "httpz-smart-contracts:0.7.0-local"
    env_file:
      - ./.env.example
    environment:
      - HARDHAT_NETWORK=${HARDHAT_NETWORK:-staging}
      - CHAIN_ID_GATEWAY=54321
    command:
      - /bin/bash
      - -c
      - |
        # Uncomment this line to debug
        # tail -f /dev/null
        cd /app/ && npx hardhat task:deployAllHostContracts
