[package]
name = "tx-sender"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
connector-utils.workspace = true
fhevm_gateway_bindings.workspace = true

actix-web.workspace = true
alloy.workspace = true
anyhow.workspace = true
prometheus.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
connector-utils = { workspace = true, features = ["tests"] }
rstest.workspace = true
serial_test.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio-stream.workspace = true
toml.workspace = true
tracing-test.workspace = true

[[bin]]
name = "tx-sender"
path = "src/bin/tx_sender.rs"
