version: '3.8'
services:
  db:
    image: postgres:15.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  coproc:
    image: ghcr.io/zama-ai/fhevm-coprocessor:v7
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50051:50051'
    volumes:
      - ${PWD}/coprocessor.key:/usr/share/coprocessor.key
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50051
      - --coprocessor-private-key=/usr/share/coprocessor.key
  geth:
    image: ghcr.io/zama-ai/geth-coprocessor-devnode:v6
    environment:
      - FHEVM_COPROCESSOR_API_KEY=a1503fb6-d79b-4e9e-826d-44cf262f3e05
      - FHEVM_COPROCESSOR_URL=coproc:50051
      - COPROCESSOR_CONTRACT_ADDRESS=0x6819e3aDc437fAf9D533490eD3a7552493fCE3B1
      - ACL_CONTRACT_ADDRESS=0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2
    ports:
      - '8745:8545'
volumes:
  db:
    driver: local
