name: kms-service
description: A helm chart to distribute and deploy the Zama KMS application stack
version: 0.6.22
apiVersion: v2
keywords:
  - kms-core
  - kms-connector
  - threshold
  - centralized
dependencies:
  - name: minio
    version: ~14.10.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
    tags:
      - local
