[package]
name = "test-harness"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace dependencies
alloy = { workspace = true }
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-kms = { workspace = true }
aws-sdk-s3 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true}
reqwest = { workspace = true}
serde_json = { workspace = true }
sqlx = { workspace = true}
testcontainers = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true}
tracing = { workspace = true }

# crates.io dependencies
base64 = "0.22.1"
k256 = { version = "0.13.4", default-features = false, features = ["pkcs8"] }

# local dependencies
fhevm-engine-common = { path = "../fhevm-engine-common" }

[features]
gpu = []
