[package]
name = "transaction-sender"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace dependencies
alloy = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-kms = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
rustls = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# Health check related additions
axum = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
humantime = { workspace = true }

# crates.io dependencies

# local dependencies
fhevm-engine-common = { path = "../fhevm-engine-common" }
fhevm_gateway_bindings = { path = "../../../gateway-contracts/rust_bindings" }

[build-dependencies]
foundry-compilers = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = ["node-bindings"] }
rstest = "0.25.0"
serial_test = { workspace = true }
testcontainers = { workspace = true }
test-harness = { path = "../test-harness" }
