name: common-pull-request

on:
  pull_request:

env:
  ACTIONLINT_VERSION: 1.7.10

permissions: {}

jobs:
  lint:
    name: common-pull-request/lint (bpr)
    permissions:
      contents: 'read' # Required to checkout repository code
      security-events: 'write' # Required to write security events for SAST results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
          fetch-depth: 0

      - name: actionlint
        uses: raven-actions/actionlint@3a24062651993d40fed1019b58ac6fbdfbf276cc # v2.0.1
        with:
            version: ${{ env.ACTIONLINT_VERSION }}

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@64418826697dcd77c93a8e4a1f7601a1942e57b5 # v3.0.18

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x

      - name: Install & run commitlint
        if: ${{ !startsWith(github.head_ref, 'mergify/merge-queue/') }}
        env:
          PR_TITLE: ${{ github.event.pull_request.title  }}
        run: |
          npm install @commitlint/config-conventional@^18 conventional-changelog-conventionalcommits @commitlint/types@^18
          npm install -g @commitlint/cli@^18
          echo "$PR_TITLE" | npx commitlint --config .github/config/commitlint.config.js --verbose

      - name: Run zizmor ðŸŒˆ
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
          persona: pedantic
          version: 1.17.0
