name: coprocessor/cargo-fmt

on:
  pull_request:

permissions: {}

jobs:
  check-changes:
    name: trigger
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-rust-files: ${{ steps.filter.outputs.rust-files }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            rust-files:
              - .github/workflows/coprocessor-cargo-fmt.yml
              - coprocessor/fhevm-engine/**
  cargo-fmt:
    name: run
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-rust-files == 'true' }}
    permissions:
      contents: 'read'
      checks: 'write'
      packages: 'read'
    runs-on: large_ubuntu_16
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: 'false'
        lfs: true

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
      with:
        toolchain: 1.89.0
        components: rustfmt

    - name: Run fmt
      run: |
        cargo fmt --all --check
      working-directory: coprocessor/fhevm-engine
