name: coprocessor-dependency-analysis

permissions: {}

on:
  pull_request:

concurrency:
  group: fhevm-coprocessor-deps-analysis-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: coprocessor-dependency-analysis/check-changes
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-rust-files: ${{ steps.filter.outputs.rust-files }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            rust-files:
              - .github/workflows/coprocessor-dependency-analysis.yml
              - coprocessor/fhevm-engine/**
  dependencies-check:
    name: coprocessor-dependency-analysis/dependencies-check (bpr)
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-rust-files == 'true' }}
    permissions:
      contents: 'read'
      checks: 'write'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Rust setup
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          toolchain: stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@84ca29d5c1719e79e23b6af147555a8f4dac79d6 # v1.10.14

      - name: Install cargo tools
        run: |
          cargo binstall --no-confirm --force \
            cargo-audit@0.21.0 \
            cargo-deny@0.16.2

      - name: Check that Cargo.lock is the source of truth
        run: |
          cd coprocessor/fhevm-engine
          cargo update -w --locked || (echo "Error: Cargo.lock is out of sync. Please run 'cargo update' locally and commit changes" && exit 1)

      - name: License whitelist
        run: |
          cd coprocessor/fhevm-engine
          cargo-deny deny check license --deny license-not-encountered

      - name: Security issue whitelist
        run: |
          cd coprocessor/fhevm-engine
          cargo-audit audit
