name: "fhEVM smart contracts Docker Image"

on:
  push:
    branches: ["amina/fhevm-sc-workflows"]
    paths:
      - .github/workflows/fhevm-smart-contracts.yml
      - contracts/**

concurrency:
  group: fhevm-smart-contracts
  cancel-in-progress: true

jobs:
  docker-smart-contracts:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-smart-contracts"
      image-dev-name: "fhevm-smart-contracts-dev"
      generate-dev-image: true
      docker-file: "ci.dockerfile"
      docker-file-dev: "dev.dockerfile"
      image-dev-description: "fhevm smart contracts dev image"
      arm-build: true

    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - docker-smart-contracts
