name: "fhEVM DB migration Docker Image"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fhevm-coprocessor.yml
      - .github/workflows/common-docker.yml
      - fhevm-engine/fhevm-db/**
  release:
    types:
      - published

concurrency:
  group: fhevm-db-migration-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  docker-db-migration:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-db-migration"
      generate-dev-image: false
      docker-file: "fhevm-engine/fhevm-db/Dockerfile"
      arm-build: true

    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - docker-db-migration
