name: gateway-contracts-hardhat-tests-docker

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true

permissions: {}

concurrency:
  group: ci-docker-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-test:
    name: gateway-contracts-hardhat-tests-docker/test (bpr)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'read'
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker image pushed by previous workflow
        run: docker pull "${IMAGE_NAME}"
        env:
          IMAGE_NAME: ${{ inputs.image-name }}

      - name: Run hardhat tests in container
        run: |
          docker run --rm -v "$(pwd)/.env.example:/app/.env" -v "$(pwd)/test:/app/test" \
            "${IMAGE_NAME}" npx hardhat test
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
