name: golden-container-images-docker-build-rust

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push the image to the registry'
        default: true
        required: true
        type: boolean
      tag:
        description: 'Tag to use for the image'
        default: 'latest'
        required: true
        type: string
  pull_request:

concurrency:
  group: golden-rust-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: golden-container-images-docker-build-rust/check-changes
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-golden-rust: ${{ steps.filter.outputs.golden-rust }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            golden-rust:
              - '.github/workflows/golden-container-images-docker-build-rust.yml'
              - 'golden-container-images/rust-glibc/**'
  set-custom-tag:
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      DOCKER_TAG_IMAGE: ${{ steps.set-tag.outputs.tag }}
    steps:
      - id: set-tag
        run: echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
  build:
    name: golden-container-images-docker-build-rust/build
    needs: [check-changes]
    if: ${{ needs.check-changes.outputs.changes-golden-rust == 'true' }}
    uses: zama-ai/ci-templates/.github/workflows/common-docker.yml@ef9d90453e0d776453026c751fbbd48e410d605a
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
      attestations: 'write'
      packages: 'write'
      id-token: 'write'
    with:
      working-directory: "."
      push_image: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true' || github.event_name != 'workflow_dispatch' && true }}
      image-name: "fhevm/gci/rust-glibc"
      docker-file: "./golden-container-images/rust-glibc/Dockerfile"
      app-cache-dir: "fhevm-golden-rust"
      ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/tags/{0}', github.event.inputs.tag) || '' }}
