name: host-contracts-publish

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Set to true for release tagging"
        type: boolean
        required: false
        default: false

permissions: {}

jobs:
  publish:
    name: host-contracts-publish/publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./host-contracts
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x

      - name: Prepare environment file
        working-directory: host-contracts
        run: cp .env.example .env

      - name: Install dependencies
        working-directory: host-contracts
        run: npm ci --include=optional

      - name: Deploy empty proxy contracts
        env:
          HARDHAT_NETWORK: hardhat
        working-directory: host-contracts
        run: npm run deploy:emptyProxies

      - name: Compile host contracts
        working-directory: host-contracts
        run: npm run compile

      - name: Compile decryption oracle
        working-directory: host-contracts
        run: npm run compile:decryptionOracle

      - name: Publish prerelease to npm
        if: ${{ inputs.release != 'true' }}
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3.1.1
        with:
          package: ./host-contracts/package.json
          tag: prerelease
          token: ${{ secrets.FHEVM_NPM_TOKEN }}
          provenance: true
          access: public

      - name: Publish release to npm
        if: ${{ inputs.release == 'true' }}
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3.1.1
        with:
          package: ./host-contracts/package.json
          token: ${{ secrets.FHEVM_NPM_TOKEN }}
          provenance: true
          access: public
