name: kms-connector-gw-listener-docker-build

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

concurrency:
  group: fhevm-kms-connector-gw-listener-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: kms-connector-gw-listener-docker-build/check-changes
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-kms-connector-gw-listener: ${{ steps.filter.outputs.kms-connector-gw-listener }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            kms-connector-gw-listener:
              - .github/workflows/kms-connector-gw-listener-docker-build.yml
              - kms-connector/crates/gw-listener/**
              - kms-connector/crates/utils/**
              - kms-connector/Cargo.toml
              - kms-connector/Cargo.lock

  build:
    name: kms-connector-gw-listener-docker-build/build
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-kms-connector-gw-listener == 'true' || github.event_name == 'release' }}
    uses: zama-ai/ci-templates/.github/workflows/common-docker.yml@e666182756172bc747d2be6e4eb9b4ed80a00a0e
    secrets:
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
      attestations: write
      packages: 'write'
      id-token: 'write'
    with:
      use-cgr-secrets: true
      working-directory: "."
      docker-context: "."
      push_image: true
      image-name: "fhevm/kms-connector/gw-listener"
      docker-file: "./kms-connector/crates/gw-listener/Dockerfile"
      app-cache-dir: "fhevm-kms-connector-gw-listener"
