name: kms-connector-common-docker-big-instance

permissions:
  contents: 'read'
  pull-requests: write
  packages: 'write'
  id-token: 'write'

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
      working-directory:
        type: string
        required: true
      docker-context:
        type: string
        required: false
        default: '.'
      push_image:
        type: boolean
        required: false
        default: true
      image-name:
        type: string
        required: true
      docker-file:
        type: string
        default: 'Dockerfile'
        required: false
      app-cache-dir:
        type: string
        required: true
    secrets:
      SLAB_ACTION_TOKEN:
        required: true
      SLAB_BASE_URL:
        required: true
      JOB_SECRET:
        required: true
      BLOCKCHAIN_ACTIONS_TOKEN:
        required: true
      AWS_ACCESS_KEY_S3_USER:
        required: true
      AWS_SECRET_KEY_S3_USER:
        required: true
    outputs:
      image_name:
        description: "Image Name with Tag generated by this task"
        value: "${{ jobs.run-docker.outputs.image_name }}"
      image_tag:
        description: "Image Tag generated by this task"
        value: "${{ jobs.run-docker.outputs.image_tag }}"

env:
  CARGO_TERM_COLOR: always

jobs:
  start-runner:
    name: kms-connector-common-docker-big-instance/start-runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner-amd64.outputs.label }}
    steps:
      - name: Start EC2 runner AMD64
        id: start-ec2-runner-amd64
        uses: zama-ai/slab-github-runner@79939325c3c429837c10d6041e4fd8589d328bac  # v1.4.1
        with:
          mode: start
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          backend: aws
          profile: docker-big-instance

  run-docker:
    name: kms-connector-common-docker-big-instance/run-docker
    needs: [start-runner]
    uses: zama-ai/ci-templates/.github/workflows/common-docker.yml@3c6b5ecf34d5350a03d1ff5e4d0ddc89607b614e
    permissions:
      actions: 'read'
      contents: 'read'
      id-token: 'write'
      pull-requests: 'read'
      packages: 'write'
      attestations: write
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
    with:
      ref: ${{ inputs.ref }}
      docker-context: ${{ inputs.docker-context }}
      working-directory: ${{ inputs.working-directory }}
      push_image: ${{ inputs.push_image }}
      runs-on-amd: ${{ needs.start-runner.outputs.label }}
      runs-on-arm: 'large_ubuntu_16_arm'
      image-name: ${{ inputs.image-name }}
      docker-file: ${{ inputs.docker-file }}
      app-cache-dir: ${{ inputs.app-cache-dir }}

  stop-runners:
    name: kms-connector-common-docker-big-instance/stop-runners
    needs:
      - start-runner
      - run-docker
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Stop AMD64 runner
        uses: zama-ai/slab-github-runner@79939325c3c429837c10d6041e4fd8589d328bac  # v1.4.1
        with:
          mode: stop
          github-token: ${{ secrets.SLAB_ACTION_TOKEN }}
          slab-url: ${{ secrets.SLAB_BASE_URL }}
          job-secret: ${{ secrets.JOB_SECRET }}
          label: ${{ needs.start-runner.outputs.label }}
