name: library-solidity-publish

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Set to true for release tagging"
        required: false
        default: false

permissions: {}

jobs:
  publish:
    name: library-solidity-publish/publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./library-solidity
    permissions:
      contents: "read" # Required to checkout repository code
      id-token: "write" # Required for OIDC authentication
      packages: "write" # Required to publish Docker images
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20.x

      - name: Update npm # required by trusted publishing
        run: npm install -g npm@11.7.0

      - name: Prepare environment file
        working-directory: library-solidity
        run: cp .env.example .env

      - name: Install dependencies
        working-directory: library-solidity
        run: npm ci --include=optional

      - name: Compile library
        working-directory: library-solidity
        run: npm run compile

      - name: Publish prerelease to npm
        if: ${{ inputs.release != 'true' }}
        uses: JS-DevTools/npm-publish@7f8fe47b3bea1be0c3aec2b717c5ec1f3e03410b # v4.1.1
        with:
          package: ./library-solidity/package.json
          tag: prerelease
          provenance: true
          access: public

      - name: Publish release to npm
        if: ${{ inputs.release == 'true' }}
        uses: JS-DevTools/npm-publish@7f8fe47b3bea1be0c3aec2b717c5ec1f3e03410b # v4.1.1
        with:
          package: ./library-solidity/package.json
          provenance: true
          access: public
