# Run tests
name: protocol-contracts-confidential-wrapper-tests

on:
  pull_request:

  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-protocol-contracts-confidential-wrapper-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check-changes:
    name: protocol-contracts-confidential-wrapper-tests/check-changes
    permissions:
      actions: 'read' # Required to read workflow run information
      contents: 'read' # Required to checkout repository code
      pull-requests: 'read' # Required to read pull request information
    runs-on: ubuntu-latest
    outputs:
      changes-protocol-contracts-confidential-wrapper: ${{ steps.filter.outputs.protocol-contracts-confidential-wrapper }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            protocol-contracts-confidential-wrapper:
              - .github/workflows/protocol-contracts-confidential-wrapper-tests.yml
              - protocol-contracts/confidential-wrapper/**
  tests:
    name: protocol-contracts-confidential-wrapper-tests/tests (bpr)
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-protocol-contracts-confidential-wrapper == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read' # Required to checkout repository code
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Install dependencies
        working-directory: protocol-contracts/confidential-wrapper
        run: npm ci
      
      - name: Run lint
        working-directory: protocol-contracts/confidential-wrapper
        run: make conformance

      - name: Run unit tests
        working-directory: protocol-contracts/confidential-wrapper
        run: make test