name: versions-check

on:
  release:
    types:
      - published

permissions: {}

jobs:
  check-versions:
    name: versions-check/check-versions
    runs-on: ubuntu-latest
    permissions:
      actions: 'read' # Required to read workflow run information
      contents: 'read' # Required to checkout repository code
      packages: 'read' # Required to read GitHub packages/container registry
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
          persist-credentials: 'false'

      - name: Check FHEVM sub-projects versions
        run: |
          python3 ci/versioning.py check "${RELEASE_TAG}"
